// ExplorerEnhancement.idl: ExplorerEnhancement 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(ExplorerEnhancement.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(be2e806b-f1ab-422f-89f7-8cd07f269cfc),
	pointer_default(unique)
]
interface INewFolderExt : IUnknown
{
};
[
	uuid(ad8e9b75-e82e-4c6a-830b-4acf8c407d6c),
	version(1.0),
]
library ExplorerEnhancementLib
{
	importlib("stdole2.tlb");
	[
		uuid(c36a65af-0a1e-4e09-9729-6da3e4e4461a)
	]
	coclass NewFolderExt
	{
		[default] interface INewFolderExt;
	};
};

import "shobjidl.idl";
